{"level": "info", "log_string": "Successfully called https://catfact.ninja/fact", "timestamp": "2024-05-14T12:06:39.560014Z", "metadata": {"source": "api3.log"}}
{"level": "success", "log_string": "Response: {'fact': 'A cat\u2019s heart beats nearly twice as fast as a human heart, at 110 to 140 beats a minute.', 'length': 88}", "timestamp": "2024-05-14T12:06:39.560014Z", "metadata": {"source": "api3.log"}}
{"level": "info", "log_string": "Successfully called https://catfact.ninja/fact", "timestamp": "2024-05-14T12:09:05.651135Z", "metadata": {"source": "api3.log"}}
{"level": "success", "log_string": "Response: {'fact': 'Many Egyptians worshipped the goddess Bast, who had a woman\u2019s body and a cat\u2019s head.', 'length': 84}", "timestamp": "2024-05-14T12:09:05.651135Z", "metadata": {"source": "api3.log"}}
{"level": "error", "log_string": "Other error occurred: HTTPSConnectionPool(host='catfact.ninja', port=443): Max retries exceeded with url: /fact (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000192CFD81490>: Failed to resolve 'catfact.ninja' ([Errno 11001] getaddrinfo failed)\"))", "timestamp": "2024-05-14T12:10:14.323239Z", "metadata": {"source": "api3.log"}}
{"level": "error", "log_string": "Other error occurred: HTTPSConnectionPool(host='catfact.ninja', port=443): Max retries exceeded with url: /fact (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000022775D91490>: Failed to resolve 'catfact.ninja' ([Errno 11001] getaddrinfo failed)\"))", "timestamp": "2024-05-14T12:31:33.714044Z", "metadata": {"source": "api3.log"}}
